### ISSUE TITLE
Compilation failed : undefined reference to `httpadmin_start'

### ISSUE THREAD

**Issue by warhole9** [donald-jackson/kannel-pluginbox#16]
Hello,
I tried to compile plugin box on ubuntu 18, Kannel 1.4.5 and I got 2 issues :

1.- make :

> /usr/bin/ld: pluginbox_plugin.o: undefined reference to symbol dlsym@@GLIBC_2.2.5
> //lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line

2.- make "LDFLAGS=-ldl"
I patch this error by adding make "LDFLAGS=-ldl"

> pluginbox.o: In function init_pluginbox:
> /usr/local/src/kannel/pluginbox/gw/pluginbox.c:877: undefined reference to httpadmin_start
> pluginbox.o: In function main:
> /usr/local/src/kannel/pluginbox/gw/pluginbox.c:931: undefined reference to httpadmin_stop

Here the complete logs of the second make :

> make  all-recursive
> make[1] : on entre dans le répertoire « /usr/local/src/kannel/pluginbox »
> Making all in gwlib
> make[2] : on entre dans le répertoire « /usr/local/src/kannel/pluginbox/gwlib »
> make[2]: rien à faire pour « all ».
> make[2] : on quitte le répertoire « /usr/local/src/kannel/pluginbox/gwlib »
> Making all in gw
> make[2] : on entre dans le répertoire « /usr/local/src/kannel/pluginbox/gw »
> /bin/bash ../libtool --tag=CC   --mode=link gcc  -g -O2 -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -I/usr/local/kannel/include/kannel -g -O2 -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_LARGE_FILES= -I/usr/include/libxml2 -I/usr/include/openssl  -ldl -o pluginbox pluginbox.o pluginbox_plugin.o  -lgwlib  -L/usr/local/kannel/lib -lgw -lwap -lgwlib -lssl -lrt -lresolv -lnsl -lm  -lpthread -lxml2 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -lcrypto -lssl
> libtool: link: gcc -g -O2 -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -I/usr/local/kannel/include/kannel -g -O2 -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_LARGE_FILES= -I/usr/include/libxml2 -I/usr/include/openssl -o pluginbox pluginbox.o pluginbox_plugin.o  -ldl -L/usr/local/kannel/lib /usr/local/kannel/lib/libgw.so /usr/local/kannel/lib/libwap.so /usr/local/kannel/lib/libgwlib.so -lrt -lresolv -lnsl -lm -lpthread -lxml2 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -lcrypto -lssl -Wl,-rpath -Wl,/usr/local/kannel/lib -Wl,-rpath -Wl,/usr/local/kannel/lib
> pluginbox.o: In function `init_pluginbox':
> /usr/local/src/kannel/pluginbox/gw/pluginbox.c:877: undefined reference to `httpadmin_start'
> pluginbox.o: In function `main':
> /usr/local/src/kannel/pluginbox/gw/pluginbox.c:931: undefined reference to `httpadmin_stop'
> collect2: error: ld returned 1 exit status
> Makefile:312: recipe for target 'pluginbox' failed
> make[2]: *** [pluginbox] Error 1
> make[2] : on quitte le répertoire « /usr/local/src/kannel/pluginbox/gw »
> Makefile:351: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1] : on quitte le répertoire « /usr/local/src/kannel/pluginbox »
> Makefile:279: recipe for target 'all' failed
> make: *** [all] Error 2

Do you have an idea about what is it doing wrong ? Maybe the order of the compilation ?

**Comment by donald-jackson** [comment]
please use latest SVN kannel to compile
