### ISSUE TITLE
how to alter the {X-Kannel-Plugin-Msg-sms-meta_data}

### ISSUE THREAD

**Issue by Suren15894** [donald-jackson/kannel-pluginbox#21]
Hello @donald-jackson ~

Is there a way we can alter the data comes from X-Kannel-Plugin-Msg-sms-meta_data?

when i try to use this header for the http plugin, this header is being flagged as no data received from the upstream.

if we can get the x-kannel-plugin-msg=sms-meta_data then we can alter the TLV's, please assist.

**Comment by m-faraz** [comment]
Hi @Suren15894 can you elaborate how you were able to solve this?
