### ISSUE TITLE
'Couldn't fetch'

### ISSUE THREAD

**Issue by jompigrande** [donald-jackson/kannel-pluginbox#6]
Hello Donald, I figure out that im having one random 'Couldn't fetch' error daily on every site, i dont have debug enabled to tell much more about this, but the weird thing it's that apache reports 200 as it was successful called the http processor:

grep '2017-01-12 17:37:54' /var/log/kannel/kannel-pluginbox.log.1
2017-01-12 17:37:54 [32047] [12] ERROR: Couldn't fetch <http://127.0.0.1/XXXXXX/http-processor.php>
2017-01-12 17:37:54 [32047] [5] WARNING: [HTTP-PLUGIN] Upstream URL (null) rejected msg with status -1 (outside >= 200 < 400), rejecting
2017-01-12 17:37:54 [32047] [5] WARNING: Plugin chain has asked us to reject this message

grep '17:37:54'  /var/log/apache2/access.log
127.0.0.1 - - [08/Jan/2017:17:37:54 -0600] "GET /XXXXXXX/http-processor.php HTTP/1.1" 200 245 "-" "-"

What did you think that can be happening, let me know if its better to enable the debug on one of the servers to give more details about this.

Regards, Jose

**Comment by donald-jackson** [comment]
Hi Jose, how heavy was the load at this time (how many messages/sec were you processing) ?

**Comment by jompigrande** [comment]
Today i have one peak of 20K messages per minute distributed in 6 servers, and it didnt throw any 'Couldn't fetch', i check graphs from 08/Jan/2017 and doesnt have that peaks at that hour, i think i will need to rise debug level and check what its happening when the error cames.

**Comment by donald-jackson** [comment]
I would suggest checking in your PHP code/Apache, I am 99.9% sure this is an issue related to your web server servicing the request. Although the timestamp you provided is the same it could be for another transaction as there are multiple in a single second.
