### ISSUE TITLE
DB support

### ISSUE THREAD

**Issue by rkluwen** [donald-jackson/kannel-pluginbox#8]
Donald, right now I've got a bunch of plugins, each with their own database support.
Would that be something to integrate in the pluginbox core?
Or add a gwlib extension to Kannel itself?
Not sure what they way to go would be here.

**Comment by rkluwen** [comment]
I'm working on a proposal now, coming up in some pull-request-to-come.

**Comment by rkluwen** [comment]
See the dbsupport2 pull-request.

**Comment by donald-jackson** [comment]
No pull request received as yet. I just wanted to add, including db support in pluginbox core would not be desirable as some people use pluginbox for other filtering/http/non-db uses. I would prefer this contained in some plugin infrastructure

**Comment by rkluwen** [comment]
The pull request was already there... Just the issue was not closed yet.
Using db support is purely optional of course.

**Comment by donald-jackson** [comment]
I'm not sure if I'm doing something stupid here, I see no pull requests/code etc anywhere on this issue or github page? :)

**Comment by rkluwen** [comment]
The pull request has already been merged as well.

**Comment by donald-jackson** [comment]
Apologies I was confusing the issues with the other one submitted. I'm getting old.
